// data.js
const characters = [
 {
 name: "高坂穗乃果",
 group: "μ's",
 subUnit: "Printemps",
 personality: "樂觀進取，擁有超強的行動力與感染力。",
 stats: "體力: 90 / 技術: 75 / 魅力: 95",
 hotStory: "為了阻止廢校，發起並成立了偶像團體。",
 mainSong: "《Someday of my life》/《Snow halation》(Center)",
 trivia: "果果的CV新田惠海在錄音時，經常會帶著蜂蜜來潤喉。",
 },
 {
 name: "高海千歌",
 group: "Aqours",
 subUnit: "CYaRon!",
 personality: "憧憬μ's，性格開朗不服輸。",
 stats: "體力: 85 / 技術: 80 / 魅力: 90",
 hotStory: "帶領 Aqours 從 0 變為 1 的奇蹟歷程。",
 mainSong: "《One More Sunshine Story》/《君のこころは輝いてるかい?》",
 trivia: "千歌家開的旅館是有現實原型的，叫安田屋旅館。",
 },
 {
 name: "上原步夢",
 group: "虹咲學園學園偶像同好會",
 subUnit: "A·ZU·NA",
 personality: "溫柔內斂，為了青梅竹馬決定踏出一步。",
 stats: "體力: 70 / 技術: 85 / 魅力: 92",
 hotStory: "在陽台上對侑的真情告白，著名的『重女』劇情（笑）。",
 mainSong: "《夢への一歩》(Solo)",
 trivia: "CV大西亞玖璃的外號是『阿古碰』，曾說過想成為步夢那樣的人。",
 },
 {
 name: "澀谷香音",
 group: "Liella!",
 subUnit: "CatChu!",
 personality: "熱愛歌唱但有舞台恐懼症，後在夥伴幫助下克服。",
 stats: "體力: 75 / 技術: 98 / 魅力: 88",
 hotStory: "與可可初次相遇並開始在街頭歌唱。",
 mainSong: "《青空を待ってる》(Solo) /《始まりは君の空》",
 trivia: "CV伊達小百合是以『一般公募』身份選拔出的，實力驚人。",
 },

 // 追加：μ's 成员
 {
 name: "絢瀨繪里",
 group: "μ's",
 subUnit: "BiBi",
 personality: "冷靜沉著，責任感強，擁有出色的芭蕾舞底子。",
 stats: "技術: 98 / 體力: 85 / 魅力: 95",
 hotStory: "從反對廢校的學生會長轉變為帶領大家的「繪里親」。",
 mainSong: "《Arifureta Kanashimi no Hate》/《Angelic Angel》",
 trivia: "CV南條愛乃同時也是 fripSide 的主唱，唱功極其深厚。",
 },
 {
 name: "東條希",
 group: "μ's",
 subUnit: "lily white",
 personality: "溫柔的大姐姐，擅長占卜，是 μ's 的命名者。",
 stats: "幸運: 99 / 技術: 80 / 魅力: 92",
 hotStory: "一直在幕後守護著穗乃果她們，是團隊的精神支柱。",
 mainSong: "《Moshimo Kara Kitano》/《Dancing stars on me!》",
 trivia: "CV楠田亞衣奈的外號是『Kussun』，和繪里的CV南條關係極好。",
 },
 {
 name: "西木野真姬",
 group: "μ's",
 subUnit: "BiBi",
 personality: "傲嬌大小姐，才華橫溢，負責曲目創作。",
 stats: "音樂: 100 / 技術: 90 / 魅力: 95",
 hotStory: "在鋼琴教室被穗乃果「捕獲」，口頭禪是『真是不明白你在說什麼』。",
 mainSong: "《Daring!!》/《Music S.T.A.R.T!!》",
 trivia: "真姬相信聖誕老人的設定是 CV Pile 在廣播中玩梗後被官方採納的。",
 },
 {
 name: "園田海未",
 group: "μ's",
 subUnit: "lily white",
 personality: "嚴謹的傳統女性，害怕羞恥的事，負責作詞。",
 stats: "體力: 92 / 技術: 95 / 魅力: 85",
 hotStory: "著名的『抽牌表情包』出處，對訓練非常嚴格。",
 mainSong: "《Watashitachi wa Mirai no Hana》/《Wild Stars》",
 trivia: "CV三森鈴子以前是音樂劇演員，舞台表現力極強。",
 },
 {
 name: "星空凜",
 group: "μ's",
 subUnit: "lily white",
 personality: "活潑開朗，像小貓一樣，運動神經發達。",
 stats: "敏捷: 98 / 體力: 95 / 魅力: 88",
 hotStory: "在時裝秀劇情中克服了不適合穿裙子的心理障礙。",
 mainSong: "《Kururin MIRACLE》/《Love wing bell》",
 trivia: "CV飯田里穗童星出身，性格跟凜一樣好動。",
 },
 {
 name: "小泉花陽",
 group: "μ's",
 subUnit: "Printemps",
 personality: "害羞內向，狂熱的偶像宅，最愛吃白飯。",
 stats: "知識: 95 / 技術: 75 / 魅力: 85",
 hotStory: "為了夢想克服膽怯，與凜、真姬一起加入社團。",
 mainSong: "《Kodoku na Heaven》/《Love marginal》",
 trivia: "CV久保由利香曾經是名模，私下非常有梗。",
 },
 {
 name: "矢澤妮可",
 group: "μ's",
 subUnit: "BiBi",
 personality: "追求極致的偶像屬性，『妮可妮可妮』發明者。",
 stats: "偶像力: 100 / 技術: 80 / 魅力: 90",
 hotStory: "曾獨自堅持偶像研究部，直到遇見穗乃果她們。",
 mainSong: "《Mahoutsukai Hajime Mashita!》/《Natsuiro Egao de 1,2,Jump!》",
 trivia: "CV德井青空是著名的動漫愛好者，還自己創作過漫畫。",
 },
 {
 name: "南小鳥",
 group: "μ's",
 subUnit: "Printemps",
 personality: "治癒系，天然呆，負責團體的服裝設計。",
 stats: "創意: 95 / 技術: 82 / 魅力: 94",
 hotStory: "在出國留學與夥伴之間抉擇的動人劇情。",
 mainSong: "《Spicaterrible》/《Wonder zone》",
 trivia: "CV內田彩的聲音非常有辨識度，被稱為『鳥神』。",
 },

 // 追加：Aqours 成员
 {
 name: "櫻內梨子",
 group: "Aqours",
 subUnit: "Guilty Kiss",
 personality: "冷靜的吐槽役，怕狗，擅長鋼琴。",
 stats: "藝術: 95 / 技術: 88 / 魅力: 90",
 hotStory: "從音乃木坂轉學到內浦，與千歌開啟了新的篇章。",
 mainSong: "《Pianoforte Monologue》/《Omoi yo Hitotsu ni Nare》",
 trivia: "CV逢田梨香子在演唱會上曾發生過鋼琴失誤，卻贏得了全員的聲援。",
 },
 {
 name: "松浦果南",
 group: "Aqours",
 subUnit: "AZALEA",
 personality: "體力驚人，性格豪爽，喜歡潛水。",
 stats: "體力: 100 / 技術: 85 / 魅力: 92",
 hotStory: "與鞠莉、黛雅之間的三年生組糾葛與和解。",
 mainSong: "《Sakana kana? Happy party train》",
 trivia: "CV諏訪奈奈香非常喜歡抱其他成員，被戲稱為『抱抱魔』。",
 },
 {
 name: "黑澤黛雅",
 group: "Aqours",
 subUnit: "AZALEA",
 personality: "學生會長，嚴謹的偶像宅，μ's 知識大師。",
 stats: "智力: 95 / 技術: 90 / 魅力: 93",
 hotStory: "雖然表面嚴厲，但其實是最希望妹妹和朋友們成功的人。",
 mainSong: "《White First Love》/《MY Mai☆TONIGHT》",
 trivia: "CV小宮有紗是特攝出身（特命戰隊），氣場十足。",
 },
 {
 name: "渡邊曜",
 group: "Aqours",
 subUnit: "CYaRon!",
 personality: "制服控，擅長跳水，口頭禪是 Yousoro!",
 stats: "運動: 98 / 技術: 85 / 魅力: 95",
 hotStory: "內心曾因千歌與梨子的親近而感到小小的寂寞。",
 mainSong: "《Beginner's Sailing》/《Koi ni Naritai AQUARIUM》",
 trivia: "CV齊藤朱夏跳舞力度非常大，被稱為『動作機器』。",
 },
 {
 name: "津島善子",
 group: "Aqours",
 subUnit: "Guilty Kiss",
 personality: "中二病少女，自稱『夜羽』，自認運氣極差。",
 stats: "運氣: 1 / 技術: 95 / 魅力: 92",
 hotStory: "在直播中展現中二魂，後被夥伴們接納了這份個性。",
 mainSong: "《In this unstable world》/《Deep Resonance》",
 trivia: "CV小林愛香唱歌非常有爆發力，跟善子一樣愛搞怪。",
 },
 {
 name: "國木田花丸",
 group: "Aqours",
 subUnit: "AZALEA",
 personality: "愛看書的文學少女，口音結尾帶 zura。",
 stats: "文學: 95 / 體力: 70 / 魅力: 88",
 hotStory: "為了支持露比而踏入偶像世界，卻發現了音樂的魅力。",
 mainSong: "《Oyasuminasan!》/《Mitaiken HORIZON》",
 trivia: "CV高槻加奈子身高是團內最高的，歌聲非常渾厚。",
 },
 {
 name: "小原鞠莉",
 group: "Aqours",
 subUnit: "Guilty Kiss",
 personality: "豪爽的混血兒，理事長，口頭禪是 Shiny!",
 stats: "財力: 99 / 技術: 88 / 魅力: 94",
 hotStory: "不惜代價也要拯救學校，並與果南重修舊好。",
 mainSong: "《New winding road》/《Water Blue New World》",
 trivia: "CV鈴木愛奈擅長民謠（民謠大賞全國冠軍），唱功驚人。",
 },
 {
 name: "黑澤露比",
 group: "Aqours",
 subUnit: "CYaRon!",
 personality: "膽小怕生，但對偶像充滿熱忱。",
 stats: "努力: 98 / 技術: 75 / 魅力: 90",
 hotStory: "在黛雅的守護下，逐漸變得堅強，能獨自上台。",
 mainSong: "《Cotton Candy Ei-Ei-Oh!》/《Awaken the power》",
 trivia: "CV降幡愛畫畫非常好，官方很多插畫都參考過她的創意。",
 }
];

 // 追加：虹咲成员
 {
 name: "中須霞",
 group: "虹咲",
 subUnit: "Qu4rtz",
 personality: "自稱世界第一可愛，愛搞小惡作劇但總失敗。",
 stats: "可愛: 100 / 技術: 82 / 魅力: 90",
 hotStory: "為了守護同好會，即便只剩一人也絕不放棄。",
 mainSong: "《Diamond》/《無敵級*Believer》",
 trivia: "CV相良茉優本人也是個 LL 鐵粉，對各團都很了解。",
 },
 {
 name: "優木雪菜",
 group: "虹咲",
 subUnit: "A·ZU·NA",
 personality: "正義感強，台上火熱台下是宅女。",
 stats: "爆發力: 99 / 技術: 98 / 魅力: 96",
 hotStory: "身兼學生會長與偶像，在理想與現實間切換。",
 mainSong: "《CHASE!》/《DIVE!》",
 trivia: "雪菜的二代CV林鼓子和初代CV楠木燈都是非常有實力的歌手。",
 },
 {
 name: "宮下愛",
 group: "虹咲",
 subUnit: "DiverDiva",
 personality: "熱情陽光，喜歡講冷笑話，交友廣泛。",
 stats: "體力: 95 / 技術: 85 / 魅力: 92",
 hotStory: "為了給別人帶來笑容而開始做偶像。",
 mainSong: "《Starlight》/《Vivid World》",
 trivia: "CV村上奈津實性格和愛醬一樣爽朗，擅長打鼓。",
 },
 {
 name: "天王寺璃奈",
 group: "虹咲",
 subUnit: "Qu4rtz",
 personality: "不擅長表情管理，使用『璃奈板』與人交流。",
 stats: "智力: 100 / 技術: 95 / 魅力: 85",
 hotStory: "研發玻璃顯示屏，終於能向大家傳達笑容。",
 mainSong: "《Dokipipo Emotion》/《First Love Again》",
 trivia: "CV田中千惠美在演唱會上真的會戴著發光的璃奈板表演。",
 },
 {
 name: "近江彼方",
 group: "虹咲",
 subUnit: "Qu4rtz",
 personality: "總是昏昏欲睡，但其實為了妹妹兼職很多工作。",
 stats: "睡眠: 100 / 技術: 90 / 魅力: 91",
 hotStory: "為了守護妹妹遙的夢想而努力的溫柔姐姐。",
 mainSong: "《Nemureru Mori ni Ikitai na》/《Butterfly》",
 trivia: "CV鬼頭明里也是《鬼滅之刃》禰豆子的配音，實力一線。",
 },
 {
 name: "艾瑪·薇德",
 group: "虹咲",
 subUnit: "Qu4rtz",
 personality: "來自瑞士，治癒人心，喜歡吃包子。",
 stats: "包容力: 100 / 技術: 88 / 魅力: 93",
 hotStory: "跨越國界，將故鄉的溫暖融入學園偶像中。",
 mainSong: "《Evergreen》/《La Bella Patria》",
 trivia: "CV指出毬亞本人很有氣質，被粉絲稱為『指出老師』。",
 },
 {
 name: "朝香果林",
 group: "虹咲",
 subUnit: "DiverDiva",
 personality: "模特兒出身，外表成熟但其實是路癡。",
 stats: "性感: 99 / 技術: 92 / 魅力: 95",
 hotStory: "支持著艾瑪的同時，也找到了自己想做的事。",
 mainSong: "《Starlight》/《Fire Bird》",
 trivia: "CV久保田未夢也是 i☆Ris 的成員，偶像經驗極其豐富。",
 },
 {
 name: "櫻坂雫",
 group: "虹咲",
 subUnit: "A·ZU·NA",
 personality: "戲劇社成員，認真乖巧，有演戲人格切換。",
 stats: "演技: 98 / 技術: 85 / 魅力: 89",
 hotStory: "在理想的自己與真實的自己之間尋找平衡。",
 mainSong: "《Anata no Risou no Heroine》/《Solitude Rain》",
 trivia: "CV前田佳織里雖然個子嬌小，但非常喜歡喝酒，酒量驚人。",
 },
 {
 name: "三船栞子",
 group: "虹咲",
 subUnit: "R3BIRTH",
 personality: "嚴肅認真，一度想廢除偶像部，後被感化。",
 stats: "效率: 95 / 技術: 90 / 魅力: 92",
 hotStory: "從追求效率到追求內心的熱情。",
 mainSong: "《Ketsui no Hikari》",
 trivia: "CV小泉萌香在直播中著名的『哈拉修』梗非常有笑點。",
 },
 {
 name: "鐘嵐珠",
 group: "虹咲",
 subUnit: "R3BIRTH",
 personality: "自我中心且充滿自信的天才偶像。",
 stats: "全能: 100 / 技術: 100 / 魅力: 98",
 hotStory: "從孤高一人到理解夥伴的意義。",
 mainSong: "《Queendom》/《Eutopia》",
 trivia: "CV法元明菜中文非常流利（曾在中國生活），是團內的中文擔當。",
 },
 {
 name: "米雅·泰勒",
 group: "虹咲",
 subUnit: "R3BIRTH",
 personality: "音樂世家出身，天才作曲家，愛吃漢堡。",
 stats: "作曲: 100 / 技術: 95 / 魅力: 90",
 hotStory: "在嵐珠的影響下，重新找回歌唱的意義。",
 mainSong: "《I'm Still...》",
 trivia: "CV內田秀出身於澳大利亞，是團內的英文擔當。",
 },
 {
 name: "鐘木優",
 group: "虹咲",
 subUnit: "無",
 personality: "同好會的核心，負責作曲與支持大家（玩家化身）。",
 stats: "執著: 100 / 魅力: 95",
 hotStory: "雖然不登台，但她是所有人的動力來源。",
 mainSong: "《Neo Sky, Neo Map!》(作曲者設定)",
 trivia: "CV矢野妃菜喜在活動中經常穿著和優一樣的制服。",
 }
];

 // 追加：Liella! 成员
 {
 name: "唐可可",
 group: "Liella!",
 subUnit: "KALEIDOSCOPE",
 personality: "來自上海，偶像發燒友，體力較弱。",
 stats: "熱情: 100 / 體力: 10 / 魅力: 95",
 hotStory: "為了在學校成立偶像部，跨海尋找歌聲的主人。",
 mainSong: "《Tiny Stars》(w/ Kanon)",
 trivia: "CV Liyuu 是知名的中國 Cosplayer，在兩地都有極高人氣。",
 },
 {
 name: "嵐千砂都",
 group: "Liella!",
 subUnit: "5yncri5e!",
 personality: "擅長街舞，丸子頭是標誌，非常努力。",
 stats: "舞蹈: 100 / 技術: 92 / 魅力: 89",
 hotStory: "為了能挺起胸膛站在香音身邊而拼命練習。",
 mainSong: "《Memories》/《Nonfiction!!》",
 trivia: "CV岬奈子外號『岬親』，性格非常溫柔。",
 },
 {
 name: "平安名菫",
 group: "Liella!",
 subUnit: "CatChu!",
 personality: "演藝圈老手，自封為 Galaxy 偶像。",
 stats: "自尊: 95 / 技術: 90 / 魅力: 92",
 hotStory: "在多次選秀失敗後，終於在 Liella! 找到了自己的位置。",
 mainSong: "《Nonfiction!!》(Center)",
 trivia: "CV Naomi Payton 是日美混血，英語也非常好。",
 },
 {
 name: "葉月戀",
 group: "Liella!",
 subUnit: "KALEIDOSCOPE",
 personality: "名門大小姐，古板嚴肅，後展現遊戲宅一面。",
 stats: "鋼琴: 95 / 技術: 92 / 魅力: 94",
 hotStory: "繼承母親的遺願，守護並熱愛著這所學校。",
 mainSong: "《Stella!》",
 trivia: "CV青山渚非常有氣質，但在廣播中經常自爆搞笑行為。",
 },
 {
 name: "櫻小路希奈子",
 group: "Liella!",
 subUnit: "5yncri5e!",
 personality: "來自北海道，純樸自然的女孩。",
 stats: "純潔: 100 / 技術: 75 / 魅力: 88",
 hotStory: "第一位加入的一年級新生，努力追趕前輩的腳步。",
 mainSong: "《Vitamin Summer!》",
 trivia: "CV鈴原希實非常努力，演唱會進步速度驚人。",
 },
 {
 name: "米蘭達·米奇",
 group: "Liella!",
 subUnit: "CatChu!",
 personality: "外冷內熱，酷愛流行時尚。",
 stats: "酷感: 95 / 技術: 90 / 魅力: 91",
 hotStory: "在香音的引導下加入了團體。",
 mainSong: "《Second Sparkle》",
 trivia: "CV藪島朱音在現實中也是個很酷的女生。",
 },
 {
 name: "若菜四季",
 group: "Liella!",
 subUnit: "5yncri5e!",
 personality: "理科少女，發明家，話很少但內心熱誠。",
 stats: "智力: 100 / 技術: 88 / 魅力: 85",
 hotStory: "為了與芽衣在一起而嘗試成為偶像。",
 mainSong: "《Second Sparkle》",
 trivia: "CV大熊和奏舞台爆發力極強，反差很大。",
 },
 {
 name: "米田芽衣",
 group: "Liella!",
 subUnit: "CatChu!",
 personality: "外表兇狠但內心極度喜愛偶像的傲嬌。",
 stats: "反差: 100 / 技術: 85 / 魅力: 89",
 hotStory: "在四季的鼓勵下坦率地面對自己的愛好。",
 mainSong: "《Second Sparkle》",
 trivia: "CV繪森彩年紀很小，非常有朝氣。",
 },
 {
 name: "鬼塚夏美",
 group: "Liella!",
 subUnit: "5yncri5e!",
 personality: "網紅 L-Tuber，愛財，精明強幹。",
 stats: "企劃力: 100 / 技術: 80 / 魅力: 91",
 hotStory: "從利用偶像賺錢到真心愛上偶像活動。",
 mainSong: "《Vitamin Summer!》",
 trivia: "CV繪森彩也負責很多宣傳工作。",
 },
 {
 name: "薇恩·瑪格麗特",
 group: "Liella!",
 subUnit: "無",
 personality: "音樂天才，傲慢但實力極強。",
 stats: "技術: 110 / 魅力: 95",
 hotStory: "從香音的對手轉變為 Liella! 的一員。",
 mainSong: "《Butterfly Wing》",
 trivia: "CV結那的聲壓非常恐怖，現場壓迫感十足。",
 }
];

const rarities = ["SSR", "SR", "R"];
