// data.js — 全41人完全版
const characters = [
 {
  name: "高坂穗乃果",
  nameJp: "高坂 穂乃果 (Kousaka Honoka)",
  quote: "ファイトだよ！ (Fightだよ！)",
  group: "μ's",
  subUnit: "Printemps",
  personality: "μ's 的發起人與靈魂核心，總是有著不顧一切向前衝的樂天精神。遇到困難時只要吃上面包就能立刻恢復元氣。",
  hotStory: "從在空無一人的禮堂唱出《START:DASH!!》，到雨中重病倒下經歷挫折，最終重新振作帶領團隊奪得大賽冠軍，書寫了真正的奇蹟。",
  mainSong: "《Snow halation》(Center) / 《Someday of my life》(Solo)",
  trivia: "聲優新田惠海擁有極強的肺活量。角色設定中，穗乃果家裡經營著和果子店「穗村」，其現實原型為著名的「竹むら」。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/honoka-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "絢瀨繪里",
  nameJp: "絢瀬 絵里 (Ayase Eli)",
  quote: "ハラショー！ (Harasho！)",
  group: "μ's",
  subUnit: "BiBi",
  personality: "擁有俄羅斯血統的學生會長。表面嚴格且難以接近，其實內心極度溫柔、充滿責任感，且意外地害怕黑暗。",
  hotStory: "最初為了保護學校而极力反對 μ's，在認清自己內心對舞台的渴望後，在希的引導下入團，成為團隊無可替代的舞蹈指導。",
  mainSong: "《Angelic Angel》(Center) / 《ありふれた悲しみの果て》(Solo)",
  trivia: "聲優南條愛乃同時是知名團體 fripSide 的主唱。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/eli-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "南小鳥",
  nameJp: "南 ことり (Minami Kotori)",
  quote: "ホノカチャーン！ (穗乃果醬！)",
  group: "μ's",
  subUnit: "Printemps",
  personality: "性格包容的天然呆少女，負責 μ's 的服裝設計。私底下其實是秋葉原傳說級的招牌女僕「Minalinsky」。",
  hotStory: "曾面臨去海外學習服裝設計與留在 μ's 之間的抉擇，最終在機場被穗乃果拉回，堅定了與大家共進退的心。",
  mainSong: "《Wonder zone》(Center) / 《ぶる〜べりぃ♡とれいん》(Solo)",
  trivia: "聲優內田彩被粉絲尊稱為「鳥神」。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/kotori2-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "園田海未",
  nameJp: "園田 海未 (Sonoda Umi)",
  quote: "ラブアローシュート！ (Love Arrow Shoot!)",
  group: "μ's",
  subUnit: "lily white",
  personality: "出身傳統日本舞家族的大和撫子。負責作詞與嚴酷的體能訓練。極度容易害羞，常常在腦內妄想並顏藝大爆發。",
  hotStory: "一開始覺得穿短裙當偶像太過羞恥。在穗乃果迷失方向準備放棄時，是她給予了最嚴厲但也最真摯的一巴掌打醒了隊長。",
  mainSong: "《だってだって噫無情》(Center) / 《私たちは未来の花》(Solo)",
  trivia: "聲優三森鈴子擁有深厚的音樂劇底子。動畫中海未在合宿時打撲克牌抽到鬼牌的極致顏藝，成為了不朽的迷因。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/umi-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "星空凜",
  nameJp: "星空 凛 (Hoshizora Rin)",
  quote: "テンション上がるにゃー！ (情緒高漲喵！)",
  group: "μ's",
  subUnit: "lily white",
  personality: "運動系元氣少女，說話句尾帶「喵」。小時候常被當成男孩子，導致對自己的女性魅力缺乏自信。",
  hotStory: "在二年級修學旅行期間被委任為臨時隊長，在花陽的鼓勵下，終於克服心魔穿上婚紗風格服裝，找回了作為女孩子的自信。",
  mainSong: "《Love wing bell》(Center) / 《恋のシグナルRin rin rin!》(Solo)",
  trivia: "聲優飯田里穗童星出道，從小學就活躍於演藝圈。凜雖然喜歡貓，但其實對貓過敏。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/rin-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "西木野真姬",
  nameJp: "西木野 真姫 (Nishikino Maki)",
  quote: "イミワカンナイ！ (莫名其妙！)",
  group: "μ's",
  subUnit: "BiBi",
  personality: "大醫院千金，傲嬌屬性點滿的才女。負責 μ's 的作曲。嘴上不坦率，其實極度渴望同伴。",
  hotStory: "獨自在音樂教室彈唱被穗乃果發現。表面上裝作不在乎，卻默默為團隊寫出了出道曲。",
  mainSong: "《Music S.T.A.R.T!!》(Center) / 《Daring!!》(Solo)",
  trivia: "聲優 Pile 是中韓混血兒，唱功紮實。真姬「相信聖誕老人」的設定源自 Pile 在廣播中的無心發言。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/maki-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "東條希",
  nameJp: "東條 希 (Tojo Nozomi)",
  quote: "希パワー注入！ (希Power注入！)",
  group: "μ's",
  subUnit: "lily white",
  personality: "神田明神的巫女，愛好塔羅牌。看似腹黑愛捉弄人，實則是全團最具母性與包容力的精神支柱。",
  hotStory: "她是「μ's」的命名者，一直在幕後暗中引導、撮合九人聚在一起，完成共同的奇蹟。",
  mainSong: "《Dancing stars on me!》(Center) / 《純愛レンズ》(Solo)",
  trivia: "聲優楠田亞衣奈與絢瀨繪里的聲優南條愛乃私交甚篤。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/nozomi-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "小泉花陽",
  nameJp: "小泉 花陽 (Koizumi Hanayo)",
  quote: "ダレカタスケテー！ (誰來救救我！)",
  group: "μ's",
  subUnit: "Printemps",
  personality: "性格極度內向的女孩，但只要提到學園偶像就會變成百科全書。超級喜歡吃白飯。",
  hotStory: "從小夢想成為偶像卻不敢跨出第一步。在凜與真姬的推動下，終於鼓起勇氣摘下眼鏡，大聲宣佈「我想做學園偶像」。",
  mainSong: "《我省略》(Center) / 《孤独なHeaven》(Solo)",
  trivia: "聲優久保由利香早期曾擔任過模特兒。動畫中對白米飯的狂熱，後來衍生出了官方的「花陽專屬白米」實體周邊販售企劃。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/hanayo-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "矢澤妮可",
  nameJp: "矢澤 にこ (Yazawa Nico)",
  quote: "にっこにっこにー♡ (Nico Nico Ni♡)",
  group: "μ's",
  subUnit: "BiBi",
  personality: "對「偶像」有著超乎常人的執著。平時有些高傲，但切換到偶像模式時無比可愛。是個非常照顧弟妹的好姐姐。",
  hotStory: "曾獨自死守偶像研究部。起初對半吊子的 μ's 充滿敵意，但在感受到她們的真心後，成為了可信賴的前輩。",
  mainSong: "《夏色えがおで1,2,Jump!》(Center) / 《にこぷり♡女子道》(Solo)",
  trivia: "聲優德井青空也從事漫畫創作。其標誌性的「Nico Nico Ni」在全球範圍內成為了現象級的出圈網路迷因。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/nico-avatar.jpg",
  themeColor: "#ff7e00",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "高海千歌",
  nameJp: "高海 千歌 (Takami Chika)",
  quote: "カンカンみかん！ (Kankan Mikan！ / 鏘鏘蜜柑！)",
  group: "Aqours",
  subUnit: "CYaRon!",
  personality: "極度憧憬 μ's 的普通少女。雖然自認沒有特殊才華，但擁有一顆絕對不服輸的心。行動力極強，是浦之星女學院閃閃發光的太陽。",
  hotStory: "經歷了東京演出的「零票」打擊後，在海灘邊留下了不甘的淚水。但也正是那一刻，她帶領 Aqours 重新起步，完成從 0 到 1 的蛻變。",
  mainSong: "《君のこころは輝いてるかい？》(Center) / 《One More Sunshine Story》(Solo)",
  trivia: "聲優伊波杏樹在 2nd Live 中親自完成了超高難度的前手翻動作（呼應《MIRACLE WAVE》劇情），成為 LoveLive! 歷史上的傳說。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/chika-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "櫻內梨子",
  nameJp: "桜内 梨子 (Sakurauchi Riko)",
  quote: "梨子ちゃん beam！ (Riko-chan Beam！ / 梨子光線！)",
  group: "Aqours",
  subUnit: "Guilty Kiss",
  personality: "從音乃木坂轉學而來的冷靜少女，擅長鋼琴。原本性格內斂，但在千歌的「糾纏」下逐漸敞開心扉。極度怕狗，私底下其實是個隱藏的同人誌愛好者。",
  hotStory: "曾因鋼琴比賽失利而陷入低谷。在第一季動畫中，為了回應千歌的期待，克服壓力在鋼琴比賽與 Aqours 的初次預選賽中達成了完美的「想念合一」。",
  mainSong: "《想いよひとつになれ》(Center) / 《Pianoforte Monologue》(Solo)",
  trivia: "聲優逢田梨香子在 1st Live 中彈奏鋼琴時曾因緊張失誤而崩潰落淚，隨後在全場粉絲與 Aqours 成員的聲援下重新完美演奏，成就了名場面。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/riko-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "松浦果南",
  nameJp: "松浦 果南 (Matsuura Kanan)",
  quote: "ハグしよ！ (Hug shiyo！ / 來抱抱吧！)",
  group: "Aqours",
  subUnit: "AZALEA",
  personality: "體力驚人、性格豪爽的潛水愛好者。作為三年級生，對後輩非常溫柔。擁有全團最強的體能與曼妙的身材，思考方式十分成熟。",
  hotStory: "曾為了保護受傷的鞠莉而主動扮黑臉解散了初代的 Aqours。在經歷了漫長的誤會與糾葛後，兩人在雨中擁抱和解，成為了全劇最感人的高光時刻之一。",
  mainSong: "《HAPPY PARTY TRAIN》(Center) / 《さかなかなんだか？》(Solo)",
  trivia: "聲優諏訪奈奈香非常喜歡抱其他成員，被戲稱為「抱抱魔」。",
  image: "",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "黑澤黛雅",
  nameJp: "黒澤 ダイヤ (Kurosawa Dia)",
  quote: "ぶっぶー！ですわ！ (Bubuu! Desuwa! / 嗶嗶！大錯特錯！)",
  group: "Aqours",
  subUnit: "AZALEA",
  personality: "浦之星女學院的學生會長，名門望族的大小姐。表面上嚴格且難以親近，實則是一個狂熱的 μ's 粉絲兼偶像宅。極度寵愛妹妹露比。",
  hotStory: "初期极力阻撓千歌成立偶像部，其實是為了避免妹妹和學妹們重蹈自己當年失敗的覆轍。暗中為 Aqours 鋪平了道路，是團隊真正的守護者。",
  mainSong: "《MY Mai☆TONIGHT》(Center) / 《WHITE FIRST LOVE》(Solo)",
  trivia: "聲優小宮有紗是特攝演員出身（曾出演《特命戰隊Go Busters》的黃戰士），氣質出眾且極具成熟魅力。",
  image: "",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "渡邊曜",
  nameJp: "渡辺 曜 (Watanabe You)",
  quote: "全速前進、ヨーソロー！ (Zensoku Zenshin, Yousoro! / 全速前進，Yousoro！)",
  group: "Aqours",
  subUnit: "CYaRon!",
  personality: "千歌的青梅竹馬，跳水隊的王牌。性格爽朗、運動萬能，對制服有著極度的狂熱，負責 Aqours 的服裝設計。口頭禪是水手用語「Yousoro」。",
  hotStory: "因為千歌與梨子關係逐漸親密，內心曾感到強烈的孤單與嫉妒。在與千歌坦誠相見並聽到「曜才是最初陪伴我的人」後，解開心結並獻上了絕佳的演出。",
  mainSong: "《恋になりたいAQUARIUM》(Center) / 《Beginner's Sailing》(Solo)",
  trivia: "聲優齊藤朱夏的舞蹈力度極大，動作乾淨俐落，被稱為 Aqours 的「舞蹈機器」。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/you-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "津島善子",
  nameJp: "津島 善子 (Tsushima Yoshiko)",
  quote: "ヨハネよ！ (Yohane yo! / 是夜羽！)",
  group: "Aqours",
  subUnit: "Guilty Kiss",
  personality: "重度中二病患者，自稱為墮天使「夜羽」（Yohane）。運氣極差，經常遭遇各種不幸。雖然极力想在高中隱藏中二病做個正常人，但總是屢屢破功。",
  hotStory: "因為中二病在學校遭到孤立，一度想放棄自我。在千歌等人的包容下，她意識到「展現真實的自己也沒關係」，從而確立了自己獨特的偶像風格。",
  mainSong: "《Deep Resonance》(Center) / 《in this unstable world》(Solo)",
  trivia: "聲優小林愛香唱歌非常有爆發力與張力。官方後來為善子推出了專屬的奇幻平行世界動畫《幻日夜羽 -鏡中暉光-》。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/kanan-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "國木田花丸",
  nameJp: "国木田 花丸 (Kunikida Hanamaru)",
  quote: "未来ずら！ (Mirai zura! / 是未來 zura！)",
  group: "Aqours",
  subUnit: "AZALEA",
  personality: "寺廟出身的文學少女。因為家裡不使用現代電子產品，所以對所有科技產物都感到驚訝。講話帶有靜岡方言口音，句尾習慣加上「zura」。",
  hotStory: "原本認為自己「毫無亮點、不適合當偶像」，只是為了支持露比才加入。在露比的反向鼓勵下，她終於承認了自己內心深處對舞台的渴望。",
  mainSong: "《未体験HORIZON》(Center) / 《おやす！你们》(Solo)",
  trivia: "聲優高槻加奈子身高 164.5cm，是 Aqours 中最高的一位。她的歌聲極具穿透力與厚度。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/hanamaru-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "小原鞠莉",
  nameJp: "小原 鞠莉 (Ohara Mari)",
  quote: "シャイニー！ (Shiny! / 閃閃發亮！)",
  group: "Aqours",
  subUnit: "Guilty Kiss",
  personality: "日美混血的大小姐，同時兼任浦之星女學院的理事長。性格開朗奔放，經常在句中夾雜誇張的英文單詞。為了守護學校不惜投入巨大的財力與精力。",
  hotStory: "曾因為腳傷與誤會與果南、黛雅分道揚鑣。歸來後以理事長身份暗中支持 Aqours，最終在雨中與果南解開了兩年的心結，三人重新找回了丟失的青春。",
  mainSong: "《New winding road》(Solo) / 《Shiny Racers》(Solo)",
  trivia: "聲優鈴木愛奈擁有深厚的民謠功底，曾獲得全日本民謠大賞冠軍。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/mari-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "黑澤露比",
  nameJp: "黒澤 ルビィ (Kurosawa Ruby)",
  quote: "がんばルビィ！ (GanbaRuby! / 露比會加油的！)",
  group: "Aqours",
  subUnit: "CYaRon!",
  personality: "膽小怕生的女孩，非常依賴姐姐黛雅。夢想是成為能讓姐姐驕傲的偶像。害怕男性，擅長裁縫，與曜一起製作服裝。",
  hotStory: "在北海道的函館，為了鼓勵姐姐們安心畢業，露比主動策劃了與 Saint Snow 成員理亞的合作舞台，展現了從躲在姐姐背後到獨當一面的巨大成長。",
  mainSong: "《Awaken the power》(雙Center之一) / 《コットンキャンディえいえいおー！》(Solo)",
  trivia: "聲優降幡愛極具繪畫天賦。她的 Solo 曲《コットンキャンディえいえいおー！》在 YouTube 上獲得了數千萬播放，成為火出圈的神曲。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/ruby3-avatar.jpg",
  themeColor: "#009fe8",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "上原步梦",
  nameJp: "上原 歩夢 (Uehara Ayumu)",
  quote: "あなたと二人で，一歩ずつ。 (想和你兩人一起，一步一步地前進。)",
  group: "虹咲",
  subUnit: "A·ZU·NA",
  personality: "侑（玩家化身）的青梅竹馬。性格溫柔乖巧，做事腳踏實地。看似柔弱，但內心對於「不想改變的關係」有著極其強烈（甚至有些沉重）的執著。",
  hotStory: "因為察覺到侑的夢想與自己漸行漸遠，產生了強烈的不安與佔有慾，在天橋上將侑撲倒並坦白心聲，成為了被粉絲津津樂道的「重女」名場面。",
  mainSong: "《夢への一歩》(Solo) / 《Awakening Promise》(Solo)",
  trivia: "聲優大西亞玖璃的外號是「阿古碰」。步夢的代表動作是雙手比出一個「A」的形狀。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/ayumu-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "中须霞",
  nameJp: "中須 かすみ (Nakasu Kasumi)",
  quote: "L-O-V-E かすみん！",
  group: "虹咲",
  subUnit: "Qu4rtz",
  personality: "自稱「世界第一可愛」的腹黑系學妹。喜歡搞小惡作劇，但因為過於笨拙常常反噬自己。討厭被叫「霞霞」（Kasukasu）。",
  hotStory: "在同好會面臨廢部危機時，她是唯一一個死守社團不願放棄的人。表面傲嬌，其實比任何人都珍視這個充滿愛與包容的地方。",
  mainSong: "《無敵級*Believer》(Solo/首張動畫PV) / 《ダイアモンド》(Solo)",
  trivia: "聲優相良茉優在試音時，因為完美展現了霞那種「有點煩人但又讓人討厭不起來」的特質而被選中。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/kasumi2-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "优木雪菜",
  nameJp: "優木 せつ菜 (Yuki Setsuna)",
  quote: "大好きを響かせましょう！ (讓最喜歡的心情響徹吧！)",
  group: "虹咲",
  subUnit: "A·ZU·NA",
  personality: "虹咲同好會的初代核心。在舞台上是熱情如火的王道偶像，在台下則是隱藏身份的學生會長（中川菜菜）兼重度御宅族。",
  hotStory: "曾因為對偶像的要求過高而導致同好會分崩離析，甚至一度想引退。在侑的開導下，重新戴上麥克風，唱出《CHASE!》宣告王者歸來。",
  mainSong: "《CHASE!》(Solo) / 《DIVE!》(Solo)",
  trivia: "雪菜經歷過聲優更替：初代聲優楠木燈因身體原因退出，由林鼓子完美接棒，兩位聲優都擁有極強的現場演唱爆發力。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/setsuna-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "天王寺璃奈",
  nameJp: "天王寺 璃奈 (Tennoji Rina)",
  quote: "璃奈ちゃんボード「にっこり」 (璃奈板「微笑」)",
  group: "虹咲",
  subUnit: "Qu4rtz",
  personality: "理科天才少女。因為天生面部肌肉不發達，無法做出表情，因此發明了「璃奈板」來表達喜怒哀樂。性格內向但非常體貼。",
  hotStory: "為了能在舞台上向觀眾傳達笑容，她運用自己的技術開發了會發光的電子「璃奈板」，成功突破了物理的限制，展現了最耀眼的微笑。",
  mainSong: "《ドキピポ☆エモーション》(Solo) / 《ツナガルコネクト》(Solo)",
  trivia: "聲優田中千惠美在現實的 Live 演出中，也曾戴著特製的 LED 發光璃奈板進行唱跳還原。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/rina-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "宫下爱",
  nameJp: "宮下 愛 (Miyashita Ai)",
  quote: "愛さん、出陣！ (愛姐，出陣！)",
  group: "虹咲",
  subUnit: "DiverDiva",
  personality: "金髮辣妹外表，實則是熱心腸的大姐姐。極度喜歡講冷笑話，交友廣泛。",
  hotStory: "從小喜歡照顧別人。在發現自己也有無法跨越的障礙時，通過偶像活動找到了與觀眾雙向救贖的道路。",
  mainSong: "《めっちゃ Going!!》(Solo) / 《Vivid World》(Solo)",
  trivia: "聲優村上奈津實性格與角色如出一轍，非常陽光，且擅長打爵士鼓。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/mia-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "近江彼方",
  nameJp: "近江 彼方 (Konoe Kanata)",
  quote: "むにゃむにゃ……遥ちゃん…… (呼噜呼噜……遙醬……)",
  group: "虹咲",
  subUnit: "Qu4rtz",
  personality: "總是昏昏欲睡。但其實是因為在家裡要照顧妹妹遙，包辦家務並瘋狂打工而睡眠不足。",
  hotStory: "為了守護妹妹遙的夢想而努力的溫柔姐姐。在舞台上化身沉睡森林的精靈，展現了作為姐姐的實力與威嚴。",
  mainSong: "《眠れる森に行きたいな》(Solo) / 《Butterfly》(Solo)",
  trivia: "聲優鬼頭明里（曾配音《鬼滅之刃》祢豆子）在演唱會上常表演「在床上唱歌」的橋段。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/emma-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "艾玛·薇德",
  nameJp: "エマ・ヴェルデ (Emma Verde)",
  quote: "ボーノ！ (Buono! / 很好吃！)",
  group: "虹咲",
  subUnit: "Qu4rtz",
  personality: "來自瑞士的留學生。性格極其溫柔包容，熱愛日本偶像文化，特別喜歡吃麵包。",
  hotStory: "作為果林身邊最溫柔的推進者，她融化了果林的心防，並將瑞士的自然風光融入了獨唱舞台。",
  mainSong: "《Evergreen》(Solo) / 《La Bella Patria》(Solo)",
  trivia: "聲優指出毬亞氣質優雅文靜，被粉絲和成員們尊稱為「指出老師」。",
  image: "",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "朝香果林",
  nameJp: "朝香 果林 (Asaka Karin)",
  quote: "準備はいいかしら？ (準備好了嗎？)",
  group: "虹咲",
  subUnit: "DiverDiva",
  personality: "擁有模特身材的性感前輩。外表成熟冷豔，實際上卻是個無可救藥的路癡，而且私下還有著少女心的一面。",
  hotStory: "一開始以「我這種人不適合當偶像」為由拒絕，直到艾瑪握住她的手，帶她走向了充滿聚光燈的《Starlight》舞台。",
  mainSong: "《Starlight》(DiverDiva) / 《VIVID WORLD》(Solo)",
  trivia: "聲優久保田未夢同時也是偶像團體 i☆Ris 的成員，舞台經驗極其豐富。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/karin2-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "樱坂雫",
  nameJp: "桜坂 しずく (Osaka Shizuku)",
  quote: "私、立派な女優になります！ (我會成為出色的女演員的！)",
  group: "虹咲",
  subUnit: "A·ZU·NA",
  personality: "話劇社兼任成員。性格認真乖巧，渴望成為理想的完美女主角，卻因此隱藏了自己真實的一面。",
  hotStory: "在霞的鼓勵下，終於卸下偽裝，在黑白舞台上與真實的自己和解，唱出了經典的《Solitude Rain》。",
  mainSong: "《あなたの理想のヒロイン》(Solo) / 《Solitude Rain》(Solo)",
  trivia: "聲優前田佳織里個子嬌小（146cm），但在綜藝節目中因極其豪爽的性格和酒量被稱為「狂犬」。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/shizuku-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "三船栞子",
  nameJp: "三船 栞子 (Mifune Shioriko)",
  quote: "私が適任です。 (我才是最合適的人選。)",
  group: "虹咲",
  subUnit: "R3BIRTH",
  personality: "嚴謹的學生會長。極度追求效率，曾認為偶像活動是在浪費學生時間而試圖廢部。",
  hotStory: "因姐姐在偶像之路上失敗而封閉了嚮往。在同好會的感化下，終於釋放熱情，展露鋒芒。",
  mainSong: "《決意の光》(Solo) / 《Ketsui no Hikari》(Solo)",
  trivia: "聲優小泉萌香在某次直播中創造了「哈拉修」的爆笑笑面。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/shioriko-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "钟岚珠",
  nameJp: "鐘 嵐珠 (Zhong Lanzhu)",
  quote: "無問題（モーマンタイ）！ (Moumantai! / 沒問題！)",
  group: "虹咲",
  subUnit: "R3BIRTH",
  personality: "來自香港的豪金大小姐。極度自信，認為能給予所有人最棒的舞台，其實內心渴望朋友。",
  hotStory: "一度試圖吞併同好會。經歷孤立與挫折後，明白了共同成長的意義，結下了真正的羈絆。",
  mainSong: "《Queendom》(Solo) / 《Eutopia》(Solo)",
  trivia: "聲優法元明菜在中國大陸生活過很長時間，普通話與粵語極度流利。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lanzhu-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "米雅·泰勒",
  nameJp: "ミア・テイラー (Mia Taylor)",
  quote: "It's a piece of cake. (小菜一碟。)",
  group: "虹咲",
  subUnit: "R3BIRTH",
  personality: "來自紐約的 14 歲天才跳級生。性格傲嬌，喜歡漢堡，擅長作曲但不愿自己唱歌。",
  hotStory: "受困於家族盛名的壓力不敢唱歌。在聽到璃奈的呼喚後，終於拿起麥克風證明了自己。",
  mainSong: "《I'm Still...》(Solo) / 《New World》(Solo)",
  trivia: "聲優內田秀出身於澳大利亞，英語發音淳粹，完美駕馭全英文曲目。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/oumi-avatar.jpg",
  themeColor: "#fb7d39",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "涩谷香音",
  nameJp: "澁谷 かのん (Shibuya Kanon)",
  quote: "私、歌が好き！ (我喜歡唱歌！)",
  group: "Liella!",
  subUnit: "CatChu!",
  personality: "結丘的創始成員。有極高音樂天賦，但因嚴重的舞台恐懼症而落榜，一度想放棄。",
  hotStory: "在可可的鼓勵下克服恐懼，在街頭唱出《Tiny Stars》。她是 Liella! 絕對的精神領袖。",
  mainSong: "《始まりは君の空》(Center) / 《Tiny Stars》(w/ 可可)",
  trivia: "聲優伊達小百合是以一般公募嶄露頭角的天才。香音家的咖啡館現實原型位於表參道。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/shiho-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "唐可可",
  nameJp: "唐 可可 (Tang Keke)",
  quote: "すばらしい声デス！ (絕妙的聲音 DESU！)",
  group: "Liella!",
  subUnit: "KALEIDOSCOPE",
  personality: "從上海跨海而來的少女。極度熱愛學園偶像，體力極差但行動力驚人。",
  hotStory: "揹負著做不出成績就要回國的壓力，與香音互相救贖，締造了偶像部的基石。",
  mainSong: "《Tiny Stars》(雙人神曲) / 《Sukini Kuretai》(Solo)",
  trivia: "聲優 Liyuu 是中國著名 Cosplayer，這是正傳首次啟用外籍聲優擔當主角。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/extra1-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "岚千砂都",
  nameJp: "嵐 千砂都 (Arashi Chisato)",
  quote: "うぃーっす！ (Wiissu！)",
  group: "Liella!",
  subUnit: "5yncri5e!",
  personality: "香音的青梅竹馬。舞蹈實力極強，性格圓滑溫柔，非常重視與香音的約定。",
  hotStory: "為了能挺起胸膛站在香音身邊，刻意保持距離進行地獄特訓，奪冠後正式加入。",
  mainSong: "《みらくるステイチューン！》(Center) / 《Memories》(Solo)",
  trivia: "聲優岬奈子非常喜歡圓形事物，性格溫柔，被愛稱為「岬親」。",
  image: "",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "平安名堇",
  nameJp: "平安名 すみれ (Heanna Sumire)",
  quote: "ギャラクシー！ (Galaxy！)",
  group: "Liella!",
  subUnit: "CatChu!",
  personality: "童星出身，自尊心高，自稱 Galaxy 偶像。表面傲慢，其實因演藝生涯受挫而自卑。",
  hotStory: "在團隊找到了認可自己的人。在《Nonfiction!!》中擔任 C 位，完成了人生的逆襲。",
  mainSong: "《ノンフィクション!!》(Center) / 《Galaxy》(Solo)",
  trivia: "聲優 Naomi Payton 是日美混血，擁有極強的 Rap 功底與舞台表現力。",
  image: "",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "叶月恋",
  nameJp: "葉月 戀 (Hazuki Ren)",
  quote: "結ヶ丘の誇りにかけて！ (賭上結丘的驕傲！)",
  group: "Liella!",
  subUnit: "KALEIDOSCOPE",
  personality: "創辦人之女。起初對偶像抱有偏見，實則因母親的過去而痛苦。私下是隱藏遊戲宅。",
  hotStory: "在找出母親當年熱愛偶像的真相後，解開心結，將學校傳統與偶像完美結合。",
  mainSong: "《Wish Song》(Center) / 《Stella!》(Solo)",
  trivia: "聲優青山渚氣質極佳，但在節目中經常有令人捧腹的搞笑發言，反差極大。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/ren-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "樱小路希奈子",
  nameJp: "桜小路 きな子 (Sakurakoji Kinako)",
  quote: "〜っす！ (〜ssu！)",
  group: "Liella!",
  subUnit: "5yncri5e!",
  personality: "來自北海道的二期生。性格純樸，體力基礎最差，但靠著不懈努力跟上了前輩。",
  hotStory: "作為第一個加入的新生承受了巨大壓力。在特訓中堅持下來，成為了連結前後輩的橋樑。",
  mainSong: "《WE WILL!!》(參與) / 《Vitamin Summer!》(Solo)",
  trivia: "聲優鈴原希實與角色一樣，是從零開始展現出驚人成長速度的代表。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/kinako-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "米田芽衣",
  nameJp: "米女 メイ (Yoneme Mei)",
  quote: "……っ (……tsu！)",
  group: "Liella!",
  subUnit: "CatChu!",
  personality: "眼神凶狠但其實是個超級偶像宅。極度傲嬌，明明想加入卻總是找藉口推脫。",
  hotStory: "在摯友四季的推動與設計下，終於無法掩飾熱愛，流淚接過了接力棒。",
  mainSong: "《Sing！Shine！Smile！》(參與) / 《Second Sparkle》(Solo)",
  trivia: "聲優薮島朱音在現實中也是個資深的 LoveLive! 粉絲。",
  image: "",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "若菜四季",
  nameJp: "若菜 四季 (Wakana Shiki)",
  quote: "……メイ。 (……Mei。)",
  group: "Liella!",
  subUnit: "5yncri5e!",
  personality: "理科天才，話非常少，對芽衣有著極度深厚（甚至有些病嬌）的感情。",
  hotStory: "為了解開芽衣的心結，主動先加入偶像部作為誘餌，展現了看似冰冷實則熱烈的友情。",
  mainSong: "《Sing！Shine！Smile！》(參與) / 《Second Sparkle》(Solo)",
  trivia: "聲優大熊和奏舞台爆發力極強，MC 時的表現非常有個人特色。",
  image: "",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "鬼塚夏美",
  nameJp: "鬼塚 夏美 (Onitsuka Natsumi)",
  quote: "オニナッツー！ (Oninatsuu！)",
  group: "Liella!",
  subUnit: "5yncri5e!",
  personality: "網紅 L-Tuber。滿腦子賺錢與點閱率，起初加入只是為了蹭熱度賺錢。",
  hotStory: "在發現大家不計回報的汗水後深受感動，徹底融入團隊並以 C 位大放異彩。",
  mainSong: "《ビタミンSUMMER！》(Center) / 《WE WILL!!》(參與)",
  trivia: "聲優繪森彩年紀非常小，卻有著與夏美一樣古靈精怪的企劃能力。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/natsumi-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "薇恩·玛格丽特",
  nameJp: "ウィーン・マルガレーテ (Wien Margarete)",
  quote: "本当の歌を教えてあげる (讓我來教你什麼才是真正的歌吧)",
  group: "Liella!",
  subUnit: "無",
  personality: "來自奧地利的音樂天才。起初以死對頭身份登場，性格高傲冷酷，實力碾壓。",
  hotStory: "被擊敗後在三期生時期正式轉入結丘，從高高在上的對手變成了共同前進的夥伴。",
  mainSong: "《Butterfly Wing》(Solo) / 《Eutopia》(Solo)",
  trivia: "聲優結那擁有極其恐怖的現場聲壓與演唱功底，初登場便震懾了全場。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/ven-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 },
 {
  name: "鬼塚冬毬",
  nameJp: "鬼塚 冬毬 (Onitsuka Tomari)",
  quote: "徹底的なデータ分析です (這是徹底的數據分析結果)",
  group: "Liella!",
  subUnit: "無",
  personality: "夏美的妹妹，三期生。極度理性的數據派，認為偶像活動也可以用精密計算達成最優解。",
  hotStory: "見證了姐姐和團隊不可量化的奇蹟後，打破了數據庫，加入了這個充滿變數的團隊。",
  mainSong: "《Jump Into the New World》(參與) / 《New World》(Solo)",
  trivia: "聲優坂倉花作為三期生加入，為團隊注入了全新的活力。",
  image: "https://raw.githubusercontent.com/laohan1126-lang/nijigacha/main/lovelive-gacha4/fuyuki-avatar.jpg",
  themeColor: "#ff7e1f",
  assets: { avatar: "", bgm: "", videoUrl: "" }
 }
];

const rarities = ["SSR", "SR", "R"];